{{- if .Values.singleuser.karpenter.enabled -}}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .Release.Name }}-karpenter
  labels: 
    tier: karpenter-jupyterhub
    app_name: {{ .Chart.Name }}
    app_version: {{ .Chart.Version | toString }}
    release: {{ .Release.Name }}
    provisioned: karpenter
spec:
  ttlSecondsUntilExpired: 2592000 # 30 Days=60*60*24*30 Seconds;
  ttlSecondsAfterEmpty: 30
  taints: {{ .Values.singleuser.karpenter.taints | toJson }}
  labels: 
    tier: karpenter-jupyterhub
    app_name: {{ .Chart.Name }}
    app_version: {{ .Chart.Version | toString }}
    release: {{ .Release.Name }}
    provisioned: karpenter
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: {{ .Values.singleuser.karpenter.requirements.instanceTypes | toJson }}
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: {{ .Values.singleuser.karpenter.requirements.zones | toJson }}
    - key: "kubernetes.io/arch"
      operator: In
      values: {{ .Values.singleuser.karpenter.requirements.arch | toJson }}
    - key: "karpenter.sh/capacity-type" 
      operator: In
      values: {{ .Values.singleuser.karpenter.requirements.capacityTypes | toJson }}
  limits:
    resources:
      cpu: {{ .Values.singleuser.karpenter.limits.cpu }}
      memory: {{ .Values.singleuser.karpenter.limits.memory }} 
  provider:
    subnetSelector: {{ .Values.singleuser.karpenter.provider.subnetSelector | toYaml | nindent 6  }}
    securityGroupSelector: {{ .Values.singleuser.karpenter.provider.securityGroupSelector | toYaml | nindent 6 }}
    tags:
        provisioned: karpenter
{{- end }}